name: CI/CD

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  backend:
    name: Backend Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Type Check
        run: npm run typecheck

      - name: Build project
        run: npm run build